# Generated by Django 5.2.1 on 2025-05-16 09:54

import libro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('autore', models.CharField(max_length=100)),
                ('anno_pubblicazione', models.IntegerField()),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='copertine_libri/')),
                ('codice_univoco', models.CharField(default=libro.models.genera_codice_univoco, editable=False, max_length=50, unique=True)),
                ('editore', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('ROMANZO', 'romanzo'), ('FANTASCIENZA', 'fantascienza'), ('BD', 'bd'), ('HOROR', 'horor'), ('ALTRO', 'altro')], default='ALTRO', max_length=12)),
            ],
        ),
    ]
