# Generated by Django 5.2.1 on 2025-05-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_alter_libro_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.CharField(blank=True, choices=[('ROMANZO', 'romanzo'), ('FANTASCIENZA', 'fantascienza'), ('BD', 'bd'), ('HOROR', 'horor'), ('ALTRO', 'altro')], default='ALTRO', max_length=12, null=True),
        ),
    ]
