# Generated by Django 5.2.1 on 2025-05-18 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_alter_libro_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='anno_pubblicazione',
            field=models.IntegerField(blank=True, max_length=4, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
