# Generated by Django 5.2.3 on 2025-07-02 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0005_libro_descrizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='anno_pubblicazione',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
